[project]
name = "question-generator"
version = "0.1.0"
description = "Automated Python programming question generator using AI"
requires-python = "^3.10"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
